### ISSUE TITLE
[Feature] - DataHub on EKS (open source data catalog)

### ISSUE THREAD

**Issue by samuelbaruffi** [awslabs/data-on-eks#101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?  
Ability to deploy [DataHub](https://datahubproject.io/) on EKS

#### Describe the solution you would like
Data-on-EKS support for [DataHub[(https://datahubproject.io/)

#### Describe alternatives you have considered
N/A

#### Additional context

- https://datahubproject.io/
- https://github.com/datahub-project/datahub

**Comment by Santhin** [comment]
@samuelbaruffi If you need any help with this case, I would love to help you or contribute somehow

**Comment by vara-bonthu** [comment]
@Santhin Are you still up for building the Datahub blueprint? All the documentation is here  https://datahubproject.io/docs/deploy/aws

**Comment by vara-bonthu** [comment]
This blueprint is now available under https://awslabs.github.io/data-on-eks/docs/blueprints/data-analytics/datahub-on-eks

**Comment by mbuotidem** [comment]
@bbgu1 @vara-bonthu - Just curious what the open search issue referenced at : https://github.com/awslabs/data-on-eks/blob/main/analytics/terraform/datahub-on-eks/datahub-addon/values/datahub_values.yaml#L243  is? 

> `datahub: `
>      `# force older version until the OpenSearch issue with latest version is resolved `
>      `version: v0.8.45`

Perhaps a link to said issue on Github so that I can follow it?

**Comment by bbgu1** [comment]
@mbuotidem  it wasn't an OpenSearch issue.   Datahub-helm has an issue with systemUpdate job getting started before the datahub-auth-secrets is created and the workaround was to disable systemUpdate, which causes a few indices missing in OpenSearch for the latest version of gms to work.   I just created a PR to update the version to the latest and remove that comment, by creating the secret first instead of waiting for auto-generation.
