### ISSUE TITLE
Error running terraform apply for emr on eks with karpenter option

### ISSUE THREAD

**Issue by AditModi** [awslabs/data-on-eks#116]
I followed the instructions on the eks GitHub repo to run emr on eks with karpenter option. However, when I ran the `terraform apply` command, I encountered the following error:

```
Error: local-exec provisioner error

with module.eks_blueprints.module.emr_on_eks["emr-data-team-b"].null_resource.update_trust_policy,
on .terraform\modules\eks_blueprints\modules\emr-on-eks\main.tf line 106, in resource "null_resource" "update_trust_policy":
106:   provisioner "local-exec" {

Error running command 'set -e
aws emr-containers update-role-trust-policy \
--cluster-name emr-eks-karpenter \
--namespace emr-data-team-b \
--role-name emr-eks-karpenter-emr-eks-data-team-b
': exec: "/bin/sh": file does not exist. Output:"
```

I tried to troubleshoot by running `pip install --upgrade awscliv2` as mentioned in the troubleshooting guide, but the error still persists. For context, I am running this on a Windows machine.

Could someone please provide guidance on how to resolve this error? Thank you.

**Comment by vara-bonthu** [comment]
@AditModi This example has been been updated now to use [EMR on EKS as submodule](https://github.com/awslabs/data-on-eks/tree/main/analytics/terraform/emr-eks-karpenter). Please checkout the latest version from Main branch and let us know for any issues

**Comment by AditModi** [comment]
Thank you for your response. I apologize for the delayed reply. I checked out the latest version from the main branch and the previous issue has been resolved. However, I am facing another issue now. I have opened a new issue for it, which you can find here: #140 .

Thank you for your help in resolving the previous issue.
