### ISSUE TITLE
Spark and Yunikorn example fails to destroy Spark operator

### ISSUE THREAD

**Issue by nabuskey** [awslabs/data-on-eks#117]
## Description

When destroying the cluster by following the instructions, terraform cannot delete the Spark operator. 

Looks like a dependency issue. We need to delete the YuniKorn scheduler last. 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following for Terraform examples:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: latest

- Terraform version: v1.3.9

- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.1
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Reproduction Code [Required]

1. `cd analytics/terraform/spark-k8s-operator`
2. `terraform init && terraform apply` 
3. Wait for it to finish provisioning
4. Attempt to destroy by following the guide: `terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve`

## Expected behavior

`terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve` should not error out.

## Actual behavior

```
module.eks_blueprints_kubernetes_addons.module.spark_k8s_operator[0].module.helm_addon.helm_release.addon[0]: Still destroying... [id=spark-operator, 4m50s elapsed]
module.eks_blueprints_kubernetes_addons.module.spark_k8s_operator[0].module.helm_addon.helm_release.addon[0]: Still destroying... [id=spark-operator, 5m0s elapsed]

Error: timed out waiting for the condition
```
The helm pre-delete hook's pod `spark-operator-webhook-cleanup` is created with its scheduler set as the yunikorn scheduler, which does not exist because it was deleted. Therefore, the job never finishes because the pod stays in pending state forever.

**Comment by vara-bonthu** [comment]
Single Terraform Destroy has been challenging for the large number of resources and these issues are intermittent. We have introduced [module level destroy](https://awslabs.github.io/data-on-eks/docs/amazon-emr-on-eks/emr-eks-yunikorn#cleanup) sequentially. This approach has resolved the the destroy issues mostly.
