### ISSUE TITLE
[Feature] Trigger  EMR on EKS jobs with Apache Airflow (MWAA)

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#13]
Feature to show how to configure and run Airflow jobs for EMR on EKS

- Add example to this [folder](https://github.com/awslabs/data-on-eks/tree/main/analytics/emr-eks-amp-amg/examples) to trigger EMR on EKS jobs using Airflow
- Write a [Blog](https://github.com/awslabs/data-on-eks/tree/main/website/blog) under blog section of Website. To deploy both EMR on EKS and MWAA examples and trigger sample Spark job

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by season1946** [comment]
@vara-bonthu, thanks for the advice. working on it now.

**Comment by vara-bonthu** [comment]
Closing issue now. New pattern has been merged with MWAA with instructions
https://awslabs.github.io/data-on-eks/docs/job-schedulers-eks/aws-managed-airflow
