### ISSUE TITLE
[Feature] Self-managed JupyterHub on EKS

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#14]
Highly scalable deployment pattern for running JupyterHub on Amazon EKS with Terraform

- Create a new JupyterHub add-on under [EKS Blueprints repo](https://github.com/aws-ia/terraform-aws-eks-blueprints)
- Create new deployment template for Terraform under https://github.com/awslabs/data-on-eks/tree/main/ai-ml/jupyterhub 
- Create a new README for deployment (Only deployment steps)
- Add a new [Website Doc](https://github.com/awslabs/data-on-eks/tree/main/website/docs/ai-ml-eks) with design diagram, deployment (refer to README here for deployment steps) and how to run sample tests etc.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rajarshighosal** [comment]
Planning to work on this one.
I have a customer who use JupyterHub extensively and this will be of interest to them as well.

**Comment by vara-bonthu** [comment]
Closing this issue. First PR has been merged. You can find the docs here https://awslabs.github.io/data-on-eks/docs/blueprints/ai-ml/jupyterhub

We are planning to add more features to this blueprint as phase-2

1/ Use Cert Manager
2/ Use External DNS
3/ Use EFS CSI Driver - Enable add-on and create dynamic EFS volumes
4/ Use Karpenter to run JupyterHub workloads
5/ Update JupyterHub images to use PySpark, Python etc.
6/ Apache Ranger Server deployment for FGAC
7/ HiveMetastore server implementation for S3 data access

**Comment by phivid** [comment]
@vara-bonthu I saw that Karpenter seems to be managed now in the stack but EFS still is accessed through NFS protocol from PV/PVC and not the EFS CSI provider. Am I right ? Is it still planned to be included in future ? Is there any issue with the CSI ? Did I miss something ? 😅🙏
