### ISSUE TITLE
[Feature] MLFlow on Amazon EKS

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#16]
Highly scalable deployment pattern for running MLFlow on Amazon EKS with Terraform

- Create new deployment template for Terraform under https://github.com/awslabs/data-on-eks/tree/main/ai-ml/mlflow
- Create a new README for deployment (Only deployment steps)
- Add a new [Website Doc](https://github.com/awslabs/data-on-eks/tree/main/website/docs/ai-ml-eks) with design diagram, deployment (refer to README here for deployment steps) and how to run sample tests etc.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by season1946** [comment]
I would like to work on it. @vara-bonthu Do you have any idea or plan for this? If so, Can I book a meeting with you for details? thanks

**Comment by vara-bonthu** [comment]
Checkout this Helm chart from mlflow team https://github.com/mlflow/mlflow/pulls?q=helm+chart
