### ISSUE TITLE
[Feature] Apache ShardingSphere on EKS

### ISSUE THREAD

**Issue by mlycore** [awslabs/data-on-eks#185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Hi community! Currently Apache ShardingSphere has several solutions as listed below:
- CloudFormation 
- Terraform
- Helm Charts
- Operator

Just want to make sure if these solutions could be submitted to data-on-eks repo ?

**Comment by vara-bonthu** [comment]
@mlycore Could you please provide more details about Apache ShardingSphere and how its beneficial for users and the usecases? We can also monitor the issue to see if others are interested on this blueprint as well.
