### ISSUE TITLE
Airflow Ingress not getting deleted 

### ISSUE THREAD

**Issue by yogikannan01** [awslabs/data-on-eks#186]
## Description

I have followed the https://awslabs.github.io/data-on-eks/docs/job-schedulers/self-managed-airflow to create the airflow infra on top of EKS with ingress controller. When I try to destroy the ingress is not getting delete, because of this the namespace also not deleting.

I am using external LoadBalancer

During deletion I have followed the below order.
terraform destroy -target="module.db" -auto-approve
terraform destroy -target="module.eks_blueprints_kubernetes_addons" -auto-approve
terraform destroy -target="module.eks_blueprints" -auto-approve
terraform destroy -auto-approve

## Versions

airflow_helm_config = {
    name             = local.airflow_name
    chart            = local.airflow_name
    repository       = "https://airflow.apache.org"
    **version          = "1.8.0"**
    namespace        = module.airflow_irsa.namespace
    create_namespace = false
    timeout          = 360
    wait             = false # This is critical setting. Check this issue -> https://github.com/hashicorp/terraform-provider-helm/issues/683
    description      = "Apache Airflow v2 Helm chart deployment configuration"
    values = [templatefile("${path.module}/values.yaml", {
      # Airflow Postgres RDS Config
      airflow_db_user = local.airflow_name
      airflow_db_name = module.db.db_instance_name
      airflow_db_host = element(split(":", module.db.db_instance_endpoint), 0)
      # S3 bucket config for Logs
      s3_bucket_name          = module.airflow_s3_bucket.s3_bucket_id
      webserver_secret_name   = local.airflow_webserver_secret_name
      airflow_service_account = local.airflow_service_account
      efs_pvc                 = local.efs_pvc
    })]

    set_sensitive = [
      {
        name  = "data.metadataConnection.pass"
        value = aws_secretsmanager_secret_version.postgres.secret_string
      }
    ]
  }

 No I am not using any workspace 
 Yes I have cleared 
 During deletion namespace is not deleting because of Ingress

## Expected behavior

All resource should be deleted including ingress.

## Airflow Describe

kubectl describe ns airflow

Name:         airflow
Labels:       kubernetes.io/metadata.name=airflow
Annotations:  <none>
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                 Message
  ----                                         ------  ------------------               ------                 -------
  NamespaceDeletionDiscoveryFailure            False   Thu, 13 Apr 2023 20:28:12 +0530  ResourcesDiscovered    All resources successfully discovered
  NamespaceDeletionGroupVersionParsingFailure  False   Thu, 13 Apr 2023 20:28:12 +0530  ParsedGroupVersions    All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              True    Thu, 13 Apr 2023 20:29:19 +0530  ContentDeletionFailed  Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: airflow for gvr: /v1, Resource=pods
  NamespaceContentRemaining                    True    Thu, 13 Apr 2023 20:28:12 +0530  SomeResourcesRemain    Some resources are remaining: ingresses.networking.k8s.io has 1 resource instances, persistentvolumeclaims. has 1 resource instances, pods. has 4 resource instances
  NamespaceFinalizersRemaining                 True    Thu, 13 Apr 2023 20:28:12 +0530  SomeFinalizersRemain   Some content in the namespace has finalizers remaining: group.ingress.k8s.aws/cloudengineering in 1 resource instances, kubernetes.io/pvc-protection in 1 resource instances

No resource quota.

## Additional context

To over come this issue, I did workaround by running the below command but it is removed from Kubernetes resource but aws resources like Load balancer, Target Group and Security group is not cleaned up.

kubectl patch ingress airflow-airflow-ingress -n airflow -p '{"metadata":{"finalizers":[]}}' --type=merge

**Comment by vara-bonthu** [comment]
@yogikannan01  Thanks for reporting the issue. We are working on upgrading the blueprint with latest Airflow version. We will validate this issue as well and fix accordingly.

**Comment by vara-bonthu** [comment]
Airflow blueprint has been updated recently. Here is the link https://awslabs.github.io/data-on-eks/docs/blueprints/job-schedulers/self-managed-airflow
Please check if this issue is reproducible

**Comment by jagpk** [comment]
@yogikannan01 we have upgraded the Airflow blueprint in #230. Please upgrade the blueprint and revert back if the issue is still reproducible.
