### ISSUE TITLE
[Feature] MongoDB on Amazon EKS

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#20]
Build a Terraform template to build and deploy scalable [MongoDB platform](https://www.mongodb.com/kubernetes) on Amazon EKS

- Terraform Template for deployment
-  If you need new Kubernetes add-ons then use [EKS Blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) to add a new add-on
- README with deployment steps
- Add a new [Website Doc](https://github.com/awslabs/data-on-eks/tree/main/website/docs/distributed-databases-eks) with design diagram, deployment (refer to README here for deployment steps) and how to run sample tests etc.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by season1946** [comment]
Hi @vara-bonthu, I am interested on this one. For MongoDB, there are three versions (community, enterprise and Atlas). Which one you would like to cover? enterprise may require the license and key I don't have and Atlas is SaaS version. So I am thinking to work on community version.
pls let me know if anything you think I should cover. I will book a meeting with you if you think it is more convenient to share ideas. Thanks.

**Comment by vara-bonthu** [comment]
The is for opting this one. Yes, the community would be better to start with, and we can provide guidelines for the MongoDB enterprise version in the docs. Ideally, we want partners to build enterprise versions in EKS.

Docs and best practices are critical for our DoEKS patterns. Let me know for any questions

**Comment by vara-bonthu** [comment]
Closing this issue as its in the ROADMAP
