### ISSUE TITLE
EMR on EKS with Karpenter fails to deploy

### ISSUE THREAD

**Issue by raykrueger** [awslabs/data-on-eks#206]
## Description

EMR on EKS with Karpenter fails to deploy. After several attempts with out of the box configuration, and with different regions and parameters the `analytics/terraform/emr-eks-karpenter` module fails to deploy.

## Versions

➜ terraform version
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0

## Reproduction Code [Required]

Follow the docs
git clone
terraform init
terraform apply

## Expected behavior

Success

## Actual behavior

The deployment will fail consistently with the following.

```
╷
│ Error: creating EMR Containers Virtual Cluster (emr-eks-karpenter-emr-data-team-a): ValidationException: Unauthorized to perform read namespace on emr-data-team-a
│ 
│   with module.emr_containers.module.emr_on_eks["emr-data-team-a"].aws_emrcontainers_virtual_cluster.this[0],
│   on ../../../workshop/modules/emr-eks-containers/emr-on-eks/main.tf line 228, in resource "aws_emrcontainers_virtual_cluster" "this":
│  228: resource "aws_emrcontainers_virtual_cluster" "this" {
│ 
╵
╷
│ Error: creating EMR Containers Virtual Cluster (emr-eks-karpenter-emr-data-team-b): ValidationException: Unauthorized to perform read namespace on emr-data-team-b
│ 
│   with module.emr_containers.module.emr_on_eks["emr-data-team-b"].aws_emrcontainers_virtual_cluster.this[0],
│   on ../../../workshop/modules/emr-eks-containers/emr-on-eks/main.tf line 228, in resource "aws_emrcontainers_virtual_cluster" "this":
│  228: resource "aws_emrcontainers_virtual_cluster" "this" {
│ 
╵
```

**Comment by vara-bonthu** [comment]
It could be an intermittent resources dependencies issue with Terraform. 

Please try deploying with install.sh script and let us know if the issue still exists.

**Comment by vara-bonthu** [comment]
@raykrueger Is this still an issue with `install.sh` script? Please close this issue if its not reproducible.

**Comment by cloudxabide** [comment]
Hey @vara-bonthu  - I ran in to the same issue as @raykrueger (MacOS, managed via brew).  Initially I did not have "helm" installed.  Reran the terraform apply and received the same error "ValidationException: Unauthorized to perform read namespace on emr-data-team-a"
Figuring I had little to loose, I ran `terraform apply` once again, and it completed successfully (with "Apply complete! Resources: 2 added, 2 changed, 0 destroyed.")
So, possibly a timing issue (as you had suggested)

**Comment by vara-bonthu** [comment]
Thanks for the update, @cloudxabide  👍
Our initial goal in creating the install.sh script was to guarantee that module-level dependencies are deployed correctly in a sequential order. It appears that these timeout issues are still occurring intermittently for some users.

As you mentioned, the only solution seems to be rerunning the "tf apply" command to resolve these issues.

**Comment by hitsub2** [comment]
The first time we run ```install.sh``` it failed with the same error as @raykrueger, but re-run the ```install.sh```, would come up with another error:

```
module.eks_data_addons.helm_release.kubecost[0]: Modifications complete after 1m52s [id=kubecost]
╷
│ Error: creating EMR Containers Virtual Cluster (emr-eks-karpenter-emr-data-team-a): ValidationException: A virtual cluster already exists in the given namespace
│
│   with module.emr_containers["data-team-a"].aws_emrcontainers_virtual_cluster.this[0],
│   on .terraform/modules/emr_containers/modules/virtual-cluster/main.tf line 20, in resource "aws_emrcontainers_virtual_cluster" "this":
│   20: resource "aws_emrcontainers_virtual_cluster" "this" {
│
╵
╷
│ Error: creating EMR Containers Virtual Cluster (emr-eks-karpenter-emr-data-team-b): ValidationException: A virtual cluster already exists in the given namespace
│
│   with module.emr_containers["data-team-b"].aws_emrcontainers_virtual_cluster.this[0],
│   on .terraform/modules/emr_containers/modules/virtual-cluster/main.tf line 20, in resource "aws_emrcontainers_virtual_cluster" "this":
│   20: resource "aws_emrcontainers_virtual_cluster" "this" {
│
╵
FAILED: Terraform apply of all modules failed

```
