### ISSUE TITLE
Spark Operator with Yunikorn terraform execution error

### ISSUE THREAD

**Issue by lusoal** [awslabs/data-on-eks#209]
## Description

Testing Spark Operator with Yunikorn breaks during installation and the region variable is not being considered. 1. During the execution of terraform using `install.sh` we should execute `terraform init` before applying any module. 2. Even providing the `region` the terraform script doesn't take that in consideration because a default variable is being defined on `variables.tf`

`variables.tf`

```hcl
variable "region" {
  description = "region"
  type        = string
  default     = "us-west-2"
}
```
So even providing the variable all the stack is being created in `us-west-2` since it is the default variable.

The `install.sh` script should include `terraform init` and `-var 'region=$AWS_DEFAULT_REGION'`

```bash
terraform init

for target in "${targets[@]}"
do
  echo "Applying module $target..."
  terraform apply -target="$target" -auto-approve
  apply_output=$(terraform apply -target="$target" -var "region=$AWS_DEFAULT_REGION" -auto-approve 2>&1)
  if [[ $? -eq 0 && $apply_output == *"Apply complete"* ]]; then
    echo "SUCCESS: Terraform apply of $target completed successfully"
  else
    echo "FAILED: Terraform apply of $target failed"
    exit 1
  fi
done
```

And I think we should remove the default variable from `variables.tf`

```hcl
variable "region" {
  description = "region"
  type        = string
}
```

```bash
for target in "${targets[@]}"
do
  echo "Applying module $target..."
  terraform apply -target="$target" -auto-approve
  apply_output=$(terraform apply -target="$target" -auto-approve 2>&1)
  if [[ $? -eq 0 && $apply_output == *"Apply complete"* ]]; then
    echo "SUCCESS: Terraform apply of $target completed successfully"
  else
    echo "FAILED: Terraform apply of $target failed"
    exit 1
  fi
done
```

This will ensure that no resources are being created in a different region than the one that we have specified.

If your request is for a new feature, please use the `Feature request` template.

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following for Terraform examples:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: Terraform v1.4.6
- Provider version(s):

## Reproduction Code

```hcl
variable "region" {
  description = "region"
  type        = string
  default     = "us-west-2"
}
```

Just follow the deployment on [Spark Operator with Yunikorn lab](https://awslabs.github.io/data-on-eks/docs/data-analytics/spark-operator-yunikorn)

## Expected behavior

Should create the resources in the specified region on `install.sh` input

## Actual behavior

Resources are being created in `us-west-2`

**Comment by vara-bonthu** [comment]
Are you using the latest version of the blueprint? https://github.com/awslabs/data-on-eks/blob/7b3d7cb92cc2006e7ce586fa190bf5fb89e9c7d2/analytics/terraform/spark-k8s-operator/install.sh#L18?

**Comment by vara-bonthu** [comment]
Thanks! Please feel free to raise a PR to fix all the install scripts. 

Users needs to make sure that variables.tf is updated according to their needs before deploying through install.sh.

**Comment by vara-bonthu** [comment]
#211 PR merged. Closing the issue now
