### ISSUE TITLE
Spark Operator with Yunikorn examples rely on undocumented S3 bucket

### ISSUE THREAD

**Issue by raykrueger** [awslabs/data-on-eks#212]
## Description

The [Spark Operator with Yunikorn SSD example](https://awslabs.github.io/data-on-eks/docs/data-analytics/spark-operator-yunikorn#nvme-ephemeral-ssd-disk-for-spark-shuffle-storage-1) relies on an undocumented S3 bucket. Specifically the `taxi-trip-execute.sh` script expects to upload data to an S3 bucket. This S3 bucket is not mentioned in the docs, and not created by the scripts or terraform modules.

**Comment by vara-bonthu** [comment]
Users can bring their own S3 bucket for running the examples or they can use the existing S3 bucket created to store Spark History server logs. 

Please feel free to update the docs to make it clear for the users. Thanks
