### ISSUE TITLE
[Feat] Add Observability section to self managed Airflow on EKS

### ISSUE THREAD

**Issue by jagpk** [awslabs/data-on-eks#240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Monitoring Airflow with Prometheus, StatsD and Grafana to troubleshoot and detect resource bottlenecks.

#### What is the outcome that you are trying to reach?

Apache Airflow monitoring can be difficult to handle. It’s critical to keep track of Airflow KPIs at various levels, including the overall organization, individual tasks, and the DAG level.

#### Describe the solution you would like

You should be able to  keep track keep track of Airflow KPIs  and individual operators and tasks that you believe are more likely to fail or require more resources.

**Comment by vara-bonthu** [comment]
@jagpk Are you still thinking about adding this feature?

**Comment by vara-bonthu** [comment]
@jagpk Any updates on this Issue? Please close this issue if its not required
