### ISSUE TITLE
[Feature] EMR on EKS with EBS as Persistent Volume

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#25]
- Create a new template to deploy EKS Cluster, Two node groups with only root volume
- Install EBS CSI driver
- Show examples to run Spark jobs with EBS PVCs
- Show the shuffle data recovery with Spark jobs. Check this issue for more details https://issues.apache.org/jira/browse/SPARK-35593

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by shwetamotwani** [comment]
Samyak Kathane has volunteered to help with this enhancement in conjunction with EKS support

**Comment by vara-bonthu** [comment]
This is now available under examples https://github.com/awslabs/data-on-eks/tree/main/analytics/terraform/emr-eks-karpenter/examples/ebs-pvc/karpenter-compute-provisioner-ebs
