### ISSUE TITLE
[emr-eks-karpenter] Insufficient Role/Rolebinding for EMR on EKS Virtual Cluster

### ISSUE THREAD

**Issue by youngjeong46** [awslabs/data-on-eks#255]
## Description

I was able to deploy the EMR on EKS with Karpenter Blueprint successfully. While checking the Role for the EMR on EKS team A, I notice that the Kubernetes role rule does not match the official [AWS doc](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html).

It is missing the following:

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "describe", "create", "edit", "delete", "annotate", "patch", "label"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "describe", "create", "edit", "delete", "annotate", "patch", "label"]

This becomes an issue when creating a Managed Endpoint, as the following error will occur:

```
"stateDetails": "Cluster does not have sufficient RBAC permissions. Please refer to https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html for proper cluster setup.",
            "failureReason": "USER_ERROR",
            "tags": {}
```

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.4.2
- Provider version(s):
```
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.8.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.22.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

1. Run `install.sh` to deploy the EMR on EKS with Karpenter blueprint.
2. Run `kubectl describe role -n emr-data-team-a emr-eks-karpenter-emr-data-team-a` to get the Policy Rule for the team role for team a.

See above.

### Terminal Output Screenshot(s)

<img width="1633" alt="Screenshot 2023-07-18 at 10 24 33 AM" src="https://github.com/awslabs/data-on-eks/assets/2121226/df9c0c2f-1c0e-44eb-a54e-02130ba75c9a">

**Comment by youngjeong46** [comment]
Upon further review, it looks to be insufficient rules on the Terraform provider. Will raise an issue there and submit a PR.

**Comment by vara-bonthu** [comment]
Thanks @youngjeong46 ! Did you mean new Terraform module(`terraform-aws-modules/emr/aws//modules/virtual-cluster`) used by our blueprints? 

Looping @bryantbiggs as well

**Comment by bryantbiggs** [comment]
thanks - Young opened an issue and looks like he is working on a PR to fix https://github.com/terraform-aws-modules/terraform-aws-emr/issues/11

**Comment by bryantbiggs** [comment]
thanks @youngjeong46 - fix is now live in v1.1.3 https://github.com/terraform-aws-modules/terraform-aws-emr/releases/tag/v1.1.3

**Comment by youngjeong46** [comment]
Thanks @bryantbiggs ! Will try this and incorporate with Managed Endpoint. Will close the issue when I can confirm it works.

**Comment by youngjeong46** [comment]
it works now. Will close.
