### ISSUE TITLE
Kafka on EKS with EBS as Persistent Volume

### ISSUE THREAD

**Issue by shwetamotwani** [awslabs/data-on-eks#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AlyIbrahim** [comment]
@vara-bonthu You can assign this issue to me

**Comment by vara-bonthu** [comment]
Please add more details to the issue. Why this issue is critical? Are there any Kubernetes operators available? Is it a recommend practice? Any reference blog or best practices to use this approach would be useful
