### ISSUE TITLE
[Feature] OSS Kubeflow on EKS

### ISSUE THREAD

**Issue by veekaly** [awslabs/data-on-eks#278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Create an EKS addon to build and deploy scalable [Kubeflow](https://www.kubeflow.org/) on Amazon EKS

#### Additional context

```[tasklist]
### Tasks
```

**Comment by veekaly** [comment]
I am working on this feature with @savallur

**Comment by rdabane** [comment]
Hello @veekaly ,
Are there any updates on this ? 
I can help with testing the feature.
