### ISSUE TITLE
PostgreSQL on EKS with EBS as Persistent Volume

### ISSUE THREAD

**Issue by shwetamotwani** [awslabs/data-on-eks#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jihed** [comment]
Hi @vara-bonthu, could assign this to me @jihed ? I can work on this.

**Comment by vara-bonthu** [comment]
Let's use either crunchydata or cloudnative-pg operator for managing PostgreSQL.

**Comment by vara-bonthu** [comment]
#127 

Taggin the PR
