### ISSUE TITLE
Updating Karpenter provisioner 

### ISSUE THREAD

**Issue by yahavb** [awslabs/data-on-eks#288]
## Description

Update the Karpenter provisioner to address compatibility issues of `aws ec2 create-network-interface`, IMDSv2 and Karpenter new labels

If your request is for a new feature, please use the `Feature request` template.

- [ *] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following for Terraform examples:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by vara-bonthu** [comment]
Closing this issue as this issue now resolved with latest PR
