### ISSUE TITLE
namespaces "jupyterhub" not found -  ~/data-on-eks/ai-ml/jark/terraform ‹feat/jark-stack›

### ISSUE THREAD

**Issue by rbarcia** [awslabs/data-on-eks#294]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration.

**When running the ./install script following tutorial, received error on missing dependency** 
When installing JupyterHUb, 
namespaces "jupyterhub" not found 
install.sh should create the ns before installing HELM Chart
BRANCH:  ~/data-on-eks/ai-ml/jark/terraform ‹feat/jark-stack›

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following for Terraform examples:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

Ran through instructions as is.  

### Terminal Output Screenshot(s)

![image](https://github.com/awslabs/data-on-eks/assets/1315852/b62e915f-446a-458b-9bb0-e59a96c32b0b)

**Comment by vara-bonthu** [comment]
@rajarshighosal @lusoal Could you please verify the issue?

**Comment by lusoal** [comment]
> @rajarshighosal @lusoal Could you please verify the issue?

Sure, let me take a look

**Comment by lusoal** [comment]
@rbarcia is this still an issue? I was looking into your branch and I was able to find the namespace being created and the DoEKS add-ons referencing this namespaces, this should force the namespace to be created before the helm is installed:

```hcl
#---------------------------------------------------------------
  # JupyterHub Add-on
  #---------------------------------------------------------------
  enable_jupyterhub = true
  jupyterhub_helm_config = {
    namespace        = kubernetes_namespace_v1.jupyterhub.id
    create_namespace = false
    values           = [file("${path.module}/helm-values/jupyterhub-values.yaml")]
  }
```

**Comment by vara-bonthu** [comment]
@askulkarni2 @rbarcia Is this still an issue? Please close if it's not

**Comment by rbarcia** [comment]
Will run again and get back to you.  I had to create the namespace manually

**Comment by askulkarni2** [comment]
I cannot reproduce. Please reopen if this happens again.
