### ISSUE TITLE
Inability to cleanup lab environment

### ISSUE THREAD

**Issue by Mrtakeiteasy** [awslabs/data-on-eks#301]
## Description

my installation of the self-managed airflow failed, and so I wanted to remove it from my environment using the cleanup.sh script. I encountered an error that was preventing me from removing all that was installed during the initial setup.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following for Terraform examples:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

## Reproduction Code [Required]

My initial installation was using tag - daily-2023.08.04 for airflow installation. Afterwards, there was a updated fix which I updated to the build daily-2023.08.18 and tried to fix my airflow lab.

Afterwards, since no progress was made, I wanted to cleanup to avoid further charges, but it failed.

Yes

branch - daily-2023.08.04
./install.sh (failed)
branch - daily-2023.08.18
./install.sh (failed)
--> ./cleanup.sh

## Expected behavior

I expected the cleanup to clear up what was created during the ./install.sh

## Actual behavior

nothing was deleted

### Terminal Output Screenshot(s)

```
phantom@phantom-pc:~/data-on-eks/schedulers/terraform/self-managed-airflow$ ./cleanup.sh 
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part
│ of an error message.
╵
╷
│ Error: Moved resource instances excluded by targeting
│ 
│ Resource instances in your current state have moved to new addresses in the latest configuration. Terraform must include those resource instances while planning in order to ensure a correct
│ result, but your -target=... options do not fully cover all of those resource instances.
│ 
│ To create a valid plan, either remove your -target=... options altogether or add the following additional target options:
│   -target="module.airflow_s3_bucket[0].data.aws_canonical_user_id.this"
│   -target="module.fluentbit_s3_bucket.data.aws_canonical_user_id.this"
│ 
│ Note that adding these options may include further additional resource instances in your plan, in order to respect object dependencies.
```

**Comment by vara-bonthu** [comment]
We've developed a `cleanup.sh` script to ensure a reverse order deletion of resources, and it's customizable to fit your specific requirements.

Regarding the error you mentioned, I've reviewed our blueprint and it appears that the code you provided is not present:

```
│   -target="module.airflow_s3_bucket[0].data.aws_canonical_user_id.this"
│   -target="module.fluentbit_s3_bucket.data.aws_canonical_user_id.this"
```
Please note that S3 buckets cannot be deleted if they are not empty.

If the issue persists, you might want to consider running `terraform destroy --auto-approve`. This command can help identify the resource causing timeouts during the destruction process. From there, you can investigate the dependencies of that resource to determine the root cause.
