### ISSUE TITLE
"Execute Sample Spark job with Karpenter" example does not work out-of-the-box

### ISSUE THREAD

**Issue by yarozen** [awslabs/data-on-eks#329]
When following the tutorial in https://awslabs.github.io/data-on-eks/docs/blueprints/data-analytics/spark-operator-yunikorn by running the "Deploying the Solution" step followed by "Execute Sample Spark job with Karpenter" the `pyspark-pi-karpenter-driver` pod in `spark-team-a` namespace is stuck pending state.
For this to work I had to do the following changes:

Add the label to the spark-compute-optimized provisioner:
```
  labels:
    NodeGroupType: SparkComputeOptimized
```

Add the taints to the spark-compute-optimized provisioner:
```
  taints:
  - effect: NoSchedule
    key: spark-compute-optimized
```
Create Service linked role for allowing the creation of Spot instances
```
> aws iam create-service-linked-role --aws-service-name spot.amazonaws.com
```

**Comment by vara-bonthu** [comment]
Thanks for raising the issue. Yes, you are right about the issue. This was changed while adding benchmark example to this repo. I will raise a PR for this fix

**Comment by vara-bonthu** [comment]
PR has been merged now. Closing the issue
