### ISSUE TITLE
External IP for LoadBalancer / Jupyterhub Not Working

### ISSUE THREAD

**Issue by Haensel-und-Gretel** [awslabs/data-on-eks#336]
## Description

Hello,

I am following the "Steps to deploy Stable Diffusion Model on Amazon EKS" from

https://aws.amazon.com/blogs/containers/deploy-generative-ai-models-on-amazon-eks/

I have sucessfully deployed
```
> kubectl get deployments -A
NAMESPACE              NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
ingress-nginx          ingress-nginx-controller                             1/1     1            1           127m
jupyterhub             hub                                                  1/1     1            1           124m
jupyterhub             proxy                                                1/1     1            1           124m
kube-system            aws-load-balancer-controller                         2/2     2            2           127m
kube-system            coredns                                              2/2     2            2           136m
kube-system            ebs-csi-controller                                   2/2     2            2           127m
kuberay-operator       kuberay-operator                                     1/1     1            1           128m
nvidia-device-plugin   nvidia-device-plugin-node-feature-discovery-master   1/1     1            1           85m
```
And the jupyterhub should be available via the external IP listed below:
```
kubectl get svc proxy-public -n jupyterhub
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)        AGE
proxy-public   LoadBalancer   172.20.253.190   k8s-jupyterh-proxypub-01f1073af8-2665748a5de57f99.elb.us-west-2.amazonaws.com   80:30730/TCP   127m
```
However it fails to be reached via my browser:
<img width="487" alt="Screenshot 2023-10-05 132903" src="https://github.com/awslabs/data-on-eks/assets/117772279/9d3dce02-de2f-414b-9627-d9b0ad178b2c">

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

```
> terraform -version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.19.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

```
git clone https://github.com/awslabs/data-on-eks.git
cd data-on-eks/ai-ml/jark-stack/terraform
export TF_VAR_huggingface_token=hf_XXXXXXXXXX
./install.sh
aws eks update-kubeconfig --name jark-stack --region us-west-2
kubectl get svc proxy-public -n jupyterhub --output jsonpath='{.status.loadBalancer.ingress[0].hostname}'
```

## Expected behavior

Should load Jupyterhub in browser using external IP indicated with ``kubectl`` command.

## Actual behavior

External IP fails to load.

**Comment by askulkarni2** [comment]
@Haensel-und-Gretel we made a change to the JARK blueprint to create `internal` Load Balancers for security reasons [here](https://github.com/awslabs/data-on-eks/blob/44cb0769afc752e57bfb2d11192ebcec1ce97389/ai-ml/jark-stack/terraform/helm-values/ingress-nginx-values.yaml#L8) and [here](https://github.com/awslabs/data-on-eks/blob/44cb0769afc752e57bfb2d11192ebcec1ce97389/ai-ml/jark-stack/terraform/helm-values/jupyterhub-values.yaml#L17). 

You can use `kubectl port-forward` to access the service endpoints or change the values to `internet-facing` in those values.yamls and re-run `./install.sh` to apply those changes (keeping in mind that this will create public facing LBs).

I will leave this ticket open for now until we update the blog post for this.

**Comment by Haensel-und-Gretel** [comment]
@askulkarni2 Thank you for the quick reply.

I replaced ``internal`` with ``internet-facing`` in each of the two lines indicated by your links and re-ran ``./install.sh``. But I'm still unable to load page.

Could you please show me what name and ports I need to include as arguments in the 
``kubectl port-forward <pod-name> <localhost-port>:<pod-port>``
 command?

Alternatively, I can wait for the updated blog.

Very much appreciate the help.

**Comment by rdabane** [comment]
I'm also running into this issue.

**Comment by rdabane** [comment]
@Haensel-und-Gretel 

I was able to start the jupyterhub by following:
kubectl port-forward -n jupyterhub proxy-6f4db9b49d-4x6qm 8090:8000

Then open in your local browser: localhost:8090

However I'm now seeing other errors:
2023-10-20T22:03:12Z [Warning] Unable to attach or mount volumes: unmounted volumes=[volume-user1], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

Event log
