### ISSUE TITLE
[Feature] Jupyterhub - Inject temporary credentials to notebooks for AWS service access

### ISSUE THREAD

**Issue by dorukozturk** [awslabs/data-on-eks#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Injecting temporary credentials to the pods, so that when the notebooks start they can talk to AWS services. 

#### Describe the solution you would like

Possibly:

1. Create a sample s3 bucket
2. Create an IAM role/policy that can only talk to that bucket
3. Create an identity pool and associate it with the user pool
4. Run custom boto code within the context of the spawner and inject key, secret, token as environment variables

![JHUB FGAC](https://github.com/awslabs/data-on-eks/assets/11761461/581505e7-edce-4e48-97d2-a31868d80900)

**Comment by vara-bonthu** [comment]
This PR has been merged. Closing the issue
