### ISSUE TITLE
Gen AI: Stable Diffusion model on Inference2 instances

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### What is the outcome that you are trying to reach?

- Create a new blueprint example to deploy **Stable Diffusion** model using Inf2 instances, Ray Serve and Streamlit app
- Create a new Gen AI doc page under https://awslabs.github.io/data-on-eks/docs/category/inference-on-eks

**Comment by ratnopamc** [comment]
I am working on this and will raise a PR soon.
