### ISSUE TITLE
[Feature] - ClickHouse on EKS

### ISSUE THREAD

**Issue by askulkarni2** [awslabs/data-on-eks#374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vara-bonthu** [comment]
Alex: Please update the ClickHouse blueprint repo link here

**Comment by vara-bonthu** [comment]
I met with CliCkHouse team and provided guidance and review comments on thier blueprint PR. We can track this issue until the blueprint is published

**Comment by linesa-dot** [comment]
https://awslabs.github.io/data-on-eks/docs/blueprints/distributed-databases/clickhouse
