### ISSUE TITLE
failed to fetch helm chart for spark-history-server

### ISSUE THREAD

**Issue by elviento** [awslabs/data-on-eks#393]
## Description

While following the steps to deploy [spark-k8s-operator](https://awslabs.github.io/data-on-eks/docs/blueprints/data-analytics/spark-operator-yunikorn) bundle I ran into the following issue.

## Versions

- Module version [Required]: v1.0.2

- Terraform version:
v1.3.5
- Provider version(s):
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

```
cd data-on-eks/analytics/terraform/spark-k8s-operator
```

```
git clone https://github.com/awslabs/data-on-eks.git

cd data-on-eks/analytics/terraform/spark-k8s-operator
chmod +x install.sh
./install.sh
```

## Expected behavior

To deploy spark-k8s-operator bundle on EKS.

## Actual behavior

Failed to deploy due to non-existent helm chart artifact.

### Terminal Output Screenshot(s)

```
Error: could not download chart: failed to fetch https://Hyper-Mesh.github.io/spark-history-server/spark-history-server-1.0.0.tgz : 404 Not Found
│
│   with module.eks_data_addons.helm_release.spark_history_server[0],
│   on .terraform/modules/eks_data_addons/spark-history-server.tf line 44, in resource "helm_release" "spark_history_server":
│   44: resource "helm_release" "spark_history_server" {
```

**Comment by vara-bonthu** [comment]
@elviento Could you please confirm if this is resolved with latest git pull?
