### ISSUE TITLE
Terraform Implementation of EMR on EKS Observability

### ISSUE THREAD

**Issue by hitsub2** [awslabs/data-on-eks#397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

[In this blog](https://aws.amazon.com/blogs/mt/monitoring-amazon-emr-on-eks-with-amazon-managed-prometheus-and-amazon-managed-grafana/), some steps about how to configure prometheus discovery is missed. A detailed step should be added as follows:

```code
cat >./monitor_driver.yaml <<EOF
 apiVersion: monitoring.coreos.com/v1
 kind: PodMonitor
 metadata:
   name: spark-driver-metrics
   labels:
     prometheus: k8s
     app.kubernetes.io/part-of: kube-prometheus
     app.kubernetes.io/name: prometheus
   namespace: emr-eks-namespace
 spec:
    selector:
       matchLabels:
         spark-role: driver
    namespaceSelector:
       matchNames:
          - emr-eks-namespace
    podMetricsEndpoints:
    - port: spark-ui
      interval: 10s
      path: /metrics/driver/prometheus/

EOF

kubectl apply -f monitor_driver.yaml -n emr-eks-namespace
```

#### Describe the solution you would like

I would like to see the complete steps supported by the terraform.

#### Describe alternatives you have considered

maunally installed prometheus and configure service discovery for the prometheus.

**Comment by vara-bonthu** [comment]
Thanks for reporting the issue. Could you please raise a PR for this fix?
