### ISSUE TITLE
Trigger jobs with argo workflow

### ISSUE THREAD

**Issue by season1946** [awslabs/data-on-eks#41]
install argo workflow in eks
use argo workflow to trigger k8s jobs
use argo workflow to trigger spark jobs
use argo workflow for emr on eks?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dalbhanj** [comment]
Have you looked at using [ACK EMR on EKS project](https://aws-controllers-k8s.github.io/community/docs/tutorials/emr-on-eks-example/) for this purpose?
