### ISSUE TITLE
JARK blueprint upgrade with latest Karpenter

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#419]

**Comment by vara-bonthu** [comment]
@ratnopamc started working on this issue.

**Comment by vara-bonthu** [comment]
@lusoal Are you making any progress on this? Any updates

**Comment by lusoal** [comment]
Hey @vara-bonthu didn't have a lot of time to do it, if people want to use the chart and upgrade their template its fine
