### ISSUE TITLE
VPC Endpoints not working for multiple blueprints 

### ISSUE THREAD

**Issue by bbgu1** [awslabs/data-on-eks#442]
## Description

With all blueprints that support creating vpc endpoints, when we enable the feature ( by setting `enable_vpc_endpoint` variable to `true`), deployment fails due to:

- for blueprints with secondary cidr for VPC, multiple private subnets exist in each of the AZs.   We can only choose 1 subnet in each AZ to create VPC endpoints.
- for blueprints using the `terraform-aws-modules/terraform-aws-security-group` module, no explicit depends_on specified in the vpc_endpoint module.   With implicit dependency and targeted apply, the security group is created first without any rule.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
1.3
- Provider version(s):
all

## Reproduction Code [Required]

changing variables.tf:

```
variable "enable_vpc_endpoints" {
  description = "Enable VPC Endpoints"
  type        = bool
  default     = true
}
```

1. destroy existing resources  ( ./cleanup.sh)
2. change enable_vpc_entpoints to true
3. run ./install.sh

## Expected behavior

VPC created with endpoints for services needed
all resources provisioned successfully

## Actual behavior

Fail to create vpc_endpoints with error:   " DuplicateSubnetsInSameZone: Found another VPC endpoint subnet in the availability zone of .."
Fail to create node group / timeout joining cluster, after adding eks vpc endpoint.

## Additional context

Also need to review all usage of `terraform-aws-modules/terraform-aws-security-group` module, replace it with plain aws-security-group module or add explicit dependency to modules depending on the security group modules.

**Comment by vara-bonthu** [comment]
I propose removing the VPC endpoints module from our DoEKS blueprints, as they are unnecessary when using public subnets. Instead, users implementing this in production can refer to the [EKS Blueprints fully private cluster](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/fully-private-cluster) pattern.

**Comment by vara-bonthu** [comment]
@bbgu1 Has this been fixed with your latest PR? Please link the PR and close the issue
