### ISSUE TITLE
Add support for AWS Batch

### ISSUE THREAD

**Issue by delagoya** [awslabs/data-on-eks#456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

AWS Batch is a managed service for handling batch and high-performance compute workloads. It works with existing EKS clusters to launch EC2 instances within a specific namespace, and places pods onto these instances to handle these types of work requests. 

AWS Batch requires your EKS cluster to be preconfigured to allow the managed services to communicate with the head node to add compute nodes and create pod specs that are placed on the launched nodes. For exact details refer to https://docs.aws.amazon.com/batch/latest/userguide/getting-started-eks.html
  
#### Describe the solution you would like

A blueprint that allows customers easy deployment of the necessary EKS and Batch components to allow for Batch to run asynchronous, high performance and batch workloads on EKS using AWS Batch managed services 

#### Describe alternatives you have considered

All other batch schedulers require customer-deployed and managed components (Kueue, Volcano, etc).  

#### Additional context

n/a

**Comment by delagoya** [comment]
We have a set of contributors identified and are targeting an initial PR for review by 3/26

**Comment by delagoya** [comment]
Comment to keep alive. Progress is being made.

**Comment by jrussell9000** [comment]
Any update on this? Comprehensive, annotated code describing (in full) how to programmatically set up Batch on EKS seems non-existent on the interwebs.

**Comment by delagoya** [comment]
Should have a PR by end of week.

**Comment by jrussell9000** [comment]
Bumping this again. I'm also curious if it's possible (and how) to use Bottlerocket on the batch nodes.

**Comment by delagoya** [comment]
This feature was implemented and merged in PR #620. Closing the issue.
