### ISSUE TITLE
Self-managed-Airflow on EKS instance operation spec question.

### ISSUE THREAD

**Issue by sayakin0519** [awslabs/data-on-eks#502]
- [ o ] ✋ I have searched the open/closed issues and my issue is not listed.

hello. I am leaving a question because I have some questions.

I'm currently building using self-managed-airflow, 

and I saw that the EKS deployment specification uses m5.xlarge.

<First Question> 
If I lower the specifications of this instance, 

will there be any significant problem in operation?

I'm thinking of lowering the specs like this.

m5.xlarge -> m5.large

And the number of Airflow DAGs currently in operation is less than 100, 

and about 20% of them are DAGs that perform work every two minutes.

<Second Question> 
Or can you tell me the recommended minimum operating instance specs?

<Third Question>
If EKS Airflow is operated using a spot instance, 
I would like to know how to reflect the preparation for interruption 
in the terraform code. 

(It is probably done using Karpenter, but it is not present 
in the current self-managed-airflow version.)

This is my first time operating Airflow with EKS, 
so please understand that it is so difficult that 
I have no choice but to leave a question here.

Thanks.

**Comment by jagpk** [comment]
@sayakin0519 - Blueprint depicts best practice of Airflow doing just the scheduling part and Spark operator doing the heavy lifting of running the Spark jobs. Hence, Airflow is deployed on always-on/On-demand managed node groups, and Spark operator uses Karpenter to provision Spot Instances for Spark executors. 
m5.xlarge instance types are chosen to accomodate Airflow and other K8s add-ons running on the managed node group nodes. Airflow values.yaml can be edited to increase or decrease the size of Airflow executors/workers based on the actual load.

**Comment by jagpk** [comment]
@sayakin0519  Feel free to reach out me on [Linkedin](https://www.linkedin.com/in/jagdeepchahal/ ) to discuss this further.

**Comment by sayakin0519** [comment]
> @sayakin0519 Feel free to reach out me on [Linkedin](https://www.linkedin.com/in/jagdeepchahal/) to discuss this further.

@jagpk I've applied to connect with you on LinkedIn! 
[Linkedin](https://www.linkedin.com/in/lookerstudio/) here is my profile.

Thanks.

**Comment by jagpk** [comment]
@sayakin0519 - please close the issue as per our discussion.
