### ISSUE TITLE
Bump EFA Plugin to v0.5.0

### ISSUE THREAD

**Issue by lindarr915** [awslabs/data-on-eks#503]
#### Describe alternatives you have considered

Bump the EFA Plugin version to v0.5.0

#### Additional context

The latest version of EFA Plugin is v0.5.0 in the docs and YAML here

https://github.com/aws-samples/aws-efa-eks
https://raw.githubusercontent.com/aws-samples/aws-efa-eks/main/manifest/efa-k8s-device-plugin.yml

**Comment by vara-bonthu** [comment]
Thanks @lindarr915 ! We deploy EFA plugin with the Helmchart from EKS data addons reo. We just need to uplift the latest version here https://github.com/aws-ia/terraform-aws-eks-data-addons/blob/c4a4d4a8f68d679aedbd610b164965d4bf57e9de/aws-efa-k8s-device-plugin.tf#L22 and it applies to all the blueprints.
