### ISSUE TITLE
ACK EMR on EKS Controller pattern and example

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#51]
- Add a new Addon for deploying EMR on EKS ACK Controller(https://github.com/aws-ia/terraform-aws-eks-ack-addons )
- Rename existing example https://github.com/awslabs/data-on-eks/tree/main/analytics/emr-eks-amp-amg to  `emr-eks-ack-controller`
- Deploy the Helm addon
- Show examples to trigger EMR on EKS jobs using ACK Controller

EMR EKS ACK Controller [doc](https://aws-controllers-k8s.github.io/community/docs/tutorials/emr-on-eks-example/)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by season1946** [comment]
@vara-bonthu  I can take this one. Since I initiated the work on terraform-aws-eks-ack-addons, it is fairly easy for me to extend it. just one question, do you know if there is a way to submit a job to EMR on EKS by kubectl command?

**Comment by vara-bonthu** [comment]
Yeah, happy for you to take it. I am renaming the first EMR on EKS example to emr-eks-ack. Let's get the first PR ready to add a emr on EKS helm chart to ACK addon repo. We can then update this pattern in DoEKS repo. 

You can use kubectl manifest provider for deploying yaml manifests to eks. 

Let's catchup on this on Monday

**Comment by dalbhanj** [comment]
@season1946 @vara-bonthu do you think we should include Argo Workflows as part of this pattern or create separate pattern for Argo? I think if we decide to include it, we can use the opt-in (enable/disable) to showcase Argo workflows. WDYT? 
Here is the [blog](https://aws.amazon.com/blogs/big-data/introducing-ack-controller-for-amazon-emr-on-eks/) that showcase Argo Workflows with ACK controller for EMR on EKS

**Comment by season1946** [comment]
@dalbhanj just saw your comments. great work in your blog!
I think we should put your argo workflows and emr on eks stuff into argo workflow sections. 
emr on eks can be triggered by different schedulers. We have an example of using MWAA for EMR on EKS.

**Comment by season1946** [comment]
feat implemented
