### ISSUE TITLE
How to run Data EKS Gen AI models with limited EC2 vCPUs service quota?

### ISSUE THREAD

**Issue by Gall-oDrone** [awslabs/data-on-eks#539]

**Comment by igrowheart** [comment]
I have the same question. Could you open this issue?

**Comment by askulkarni2** [comment]
Hi folks! It is possible to run some LLMs like MIstral-7B-Instruct-v0.3 on smaller inferentia instance. E.g.  here are the steps you will need for using vllm ([patched](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/transformers-neuronx/transformers-neuronx-developer-guide-for-continuous-batching.html#vllm-v0-5-0-neuron-patch)) to run the Mistral-7B model:

1. launch a k8s job that:
  a. requests for inf2.8xlarge using Karpenter
  b. download, and compile LLM model from HF

      ```python -m vllm.entrypoints.openai.api_server --model mistralai/Mistral-7B-Instruct-v0.3 --max-model-len 8196 --device neuron --tensor-parallel-size 2 --max-num-seqs 4```

    c. upload the Mistral-7B-Instruct-v0.3/-split and neuron cache to S3 or HuggingFace

2. inference on inf2.xlarge
  a. download image/cache to a local container directory using an init container
  b. launch vllm

**Comment by igrowheart** [comment]
Thanks @askulkarni2, does this also support llama3? As we cannot find any guide covering llama3 with inf2.xlarge or 2xlarge.

**Comment by askulkarni2** [comment]
I haven't tried with Llama3 but it would be similar.
