### ISSUE TITLE
[Feat] Observability on Spark on EKS

### ISSUE THREAD

**Issue by season1946** [awslabs/data-on-eks#54]
- Provide guidance on Spark history server
- Monitor spark applications with Prometheus (or AMP)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vara-bonthu** [comment]
We already have guidance for deploying Spark history server https://github.com/awslabs/data-on-eks/blob/8d3021d9284f601e9417d278bf599eb4b10fd619/analytics/spark-k8s-operator/addons.tf#L115. This blueprint also writes the metrics to AMP which can be consumed by Grafana dashboards.

Let me know if you want to see anything else

**Comment by season1946** [comment]
@vara-bonthu it is mainly for documentation. I am thinking to create a web page to summarize how to monitor spark app using history server, spark web ui, prometheus and grafana (like snapshot below)
we can reuse the code in [spark-k8s-operator] and only check in some sample yaml code for demo purpose (like taxi driver one)
pls let me know your opinion. thx

![image](https://user-images.githubusercontent.com/17306003/201362539-1f2e6424-9499-4cce-8b72-7254ae433e59.png)

**Comment by vara-bonthu** [comment]
Nice one! This will make it lot easier for users

**Comment by season1946** [comment]
implemented
