### ISSUE TITLE
Support S3 gateway endpoint for EMR on EKS

### ISSUE THREAD

**Issue by hitsub2** [awslabs/data-on-eks#553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

In data scenarios, accessing s3 would have a high cost for network traffic.By gateway endpoint for s3, we can reduce the cost which will benefit the customer.

#### Describe the solution you would like

Implementing s3 gateway endpoint for emr on eks.

**Comment by vara-bonthu** [comment]
The S3 Gateway endpoint is included in the blueprint. Check the code here: [vpc.tf#L93](https://github.com/awslabs/data-on-eks/blob/a84f3b2416eb4f59765179e21d8aa6da0d7d3583/analytics/terraform/emr-eks-karpenter/vpc.tf#L93).

By default, it is disabled. To enable the endpoints, update the configuration from this link: [variables.tf#L40](https://github.com/awslabs/data-on-eks/blob/a84f3b2416eb4f59765179e21d8aa6da0d7d3583/analytics/terraform/emr-eks-karpenter/variables.tf#L40).
