### ISSUE TITLE
[jupyterhub] Minimum core managed nodes must be >= 4 ?

### ISSUE THREAD

**Issue by asmacdo** [awslabs/data-on-eks#556]
We’ve set our desired nodes and min nodes to 1, but we still have 4 nodes. 

Is there additional configuration that overrides this?

https://github.com/awslabs/data-on-eks/blob/9e52517badf3d3bca758544f09d1f905c07eec0f/ai-ml/jupyterhub/main.tf#L119

**Comment by vara-bonthu** [comment]
Changing the [desired_size](https://github.com/awslabs/data-on-eks/blob/9e52517badf3d3bca758544f09d1f905c07eec0f/ai-ml/jupyterhub/main.tf#L131) after the cluster is deployed with Terraform will not have any impact. 

To make changes effective, you need to set the [min_size](https://github.com/awslabs/data-on-eks/blob/9e52517badf3d3bca758544f09d1f905c07eec0f/ai-ml/jupyterhub/main.tf#L129) value to 1. The `desired_size` is managed by Auto Scaling Groups (ASGs) once the node groups are created.

You can modify this from AWS Console to edit the managed node groups min and desired
