### ISSUE TITLE
Add AWS Analytics Reference Architecture CDK Constructs for EMR on EKS

### ISSUE THREAD

**Issue by vgkowski** [awslabs/data-on-eks#56]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

CDK Constructs for easy deployment of [EMR on EKS ](https://constructs.dev/packages/aws-analytics-reference-architecture/v/2.4.9/api/EmrEksCluster?lang=python)and [EMR Studio with EMR on EKS ](https://constructs.dev/packages/aws-analytics-reference-architecture/v/2.4.9/api/NotebookPlatform?lang=python) already exists in the [AWS Analytics Reference Architecture](https://github.com/aws-samples/aws-analytics-reference-architecture). The CDK Constructs include automation on EKS to implement best practices related to workload isolation, autoscaling, spot, local shuffle performance optimization... 
We should reference this content to help customers using CDK to bootstrap EMR on EKS.

#### Describe the solution you would like

Add a readme in the `analytics` folder of this repository to reference the CDK Constructs. Or add a page in the `website` to reference the CDK Constructs.

**Comment by vara-bonthu** [comment]
@vgkowski  Thanks for providing the details of EMR on EKS Reference Architecture with CDK. 
Happy for you to raise a PR with Doc referring to this architecture. Let me know if you need any feedback.

Here is the location for the doc. You can use one of the existing `.md` file to create a new one. You can test the doc site locally by running the following commands

```
# Intall nodejs
cd website
npm install
npm run start
```
You should see the docs under  http://localhost:3000/. Once you are happy with the format then you can raise a PR.

**Comment by lmouhib** [comment]
This PR close this https://github.com/awslabs/data-on-eks/pull/75
