### ISSUE TITLE
NVIDIA NIM LLM Hosting Pattern 

### ISSUE THREAD

**Issue by hustshawn** [awslabs/data-on-eks#560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

NVIDIA NIM pvovides an easy way to self-host LLMs with containers. AWS can provide series of solutions to help customer to deploy the NIM provided LLMs in a performant and cost optimized way with EKS, Karpenter, Spot etc.
Would like to have a pattern for the customer to easily deploy the NIM LLMs in AWS.

#### Describe the solution you would like

Provide a IaC pattern in Data on EKS to showcase deploy NVIDIA NIM provided LLMs. Will use Karpenter, Spot, and Bottlerocket with image caching techniques which I introduced in this [AWS blog](https://aws.amazon.com/blogs/containers/reduce-container-startup-time-on-amazon-eks-with-bottlerocket-data-volume/). 

#### Additional context

NVIDIA NIM: https://www.nvidia.com/en-us/ai/
Features and architecture: https://docs.nvidia.com/nim/large-language-models/latest/introduction.html

**Comment by vara-bonthu** [comment]
This will be a great addition. 

**Step1: Leverage Existing Terraform Blueprint:**
Utilize the existing [Terraform blueprint](https://github.com/awslabs/data-on-eks/tree/main/ai-ml/nvidia-triton-server) to set up infrastructure components like EKS Cluster, Karpenter, and other addons. Update this template if required specific to Bottlerocket implementation etc.

**Step2: Add a New Folder:**
Create a new folder under [gen-ai](https://github.com/awslabs/data-on-eks/tree/main/gen-ai/inference) named nvidia-nims.
Place all the necessary code for your blueprint in this folder.

**Step3: Create Documentation:**
Add a new documentation file under the [Website docs](https://github.com/awslabs/data-on-eks/tree/main/website/docs/gen-ai/inference) with the naming convention `nvidia-nim-<modelname>`.

**Comment by hustshawn** [comment]
Thank you @vara-bonthu . I am gonna implement it, please feel free to assign this to me. I raise a PR once it is finished.
