### ISSUE TITLE
Jupyterhub with OIDC Example

### ISSUE THREAD

**Issue by omrishiv** [awslabs/data-on-eks#576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We should have an example of how to set up Jupyterhub with OIDC. Keycloak would be a good candidate that can then be swapped for Dex or Okta, or any other OIDC provider. 

#### Describe the solution you would like

An implementation of Jupyterhub that illustrates OIDC connectivity

**Comment by vara-bonthu** [comment]
Closing the issue since the feature has been merged! Thanks @omrishiv
