### ISSUE TITLE
Add CloudFlare Analytics to website

### ISSUE THREAD

**Issue by linesa-dot** [awslabs/data-on-eks#593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Collect page views and other analytics data on the DoEKS website to track overall visitors and also understand which patterns are the most trafficked by our users.

#### Describe the solution you would like

https://developers.cloudflare.com/analytics/web-analytics/

**Comment by candonov** [comment]
Pls assign to me.

**Comment by candonov** [comment]
Implemented https://github.com/awslabs/data-on-eks/pull/703
