### ISSUE TITLE
Create blueprint using S3 mountpoint for external jar files to run Spark workloads

### ISSUE THREAD

**Issue by ratnopamc** [awslabs/data-on-eks#598]
### Community Note
For Spark workloads requiring additional JARs, it's unnecessary to include these JARs in the base Docker image. These JARs can be developed and maintained by multiple teams and stored in an S3 bucket. Spark Operator or Spark jobs can reference these JARs from S3 using S3 mountpoint.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Problem Statement
Image Size: The Docker images are getting larger with the increasing number of JARs added.
Container Start Time: The startup time of containers is slowing down due to the loading of multiple JARs.
Continuous Updates: Updating these JARs requires recreating the images, which is time-consuming. Managing versions for each JAR is also challenging.

#### Describe the solution you would like
Developers will continue to generate the latest JARs and store them with tags or versions in the S3 bucket.
The Spark application will specify the appropriate tag of the JAR in the job specification.
The S3 mountpoint will be dynamically configured by the CSI driver to mount the S3 bucket to each node, specifying the path to the JARs location.
Spark jobs submitted to EKS will read the JARs from S3, as it is mounted as a local drive in the pods via S3 mountpoint (e.g., /opt/spark/jars/...).
Enable caching with the S3 mountpoint to store the JARs on the node. This allows new executors to load the JARs faster than reading directly from the S3 bucket each time.

**Comment by askulkarni2** [comment]
@ratnopamc let's do this in the existing spark blueprint.

**Comment by ratnopamc** [comment]
@vara-bonthu, an we close this since the PR is merged?

**Comment by askulkarni2** [comment]
Fixed in #606
