### ISSUE TITLE
Run llmperf as a container for benchmarking Ray vLLM Inference

### ISSUE THREAD

**Issue by ratnopamc** [awslabs/data-on-eks#660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Run [llmperf](https://github.com/ray-project/llmperf) as a container for running benchmarks.

#### Describe the solution you would like

Instead of running llmperf on local, deploy and run it as container.
Export the generated report as a file (.json or .csv).

#### Additional context

https://awslabs.github.io/data-on-eks/docs/gen-ai/inference/Neuron/vllm-ray-inf2#performance-benchmarking-with-llmperf-tool

**Comment by sindhupalakodety** [comment]
Interested to work on it.

**Comment by ratnopamc** [comment]
Thanks @sindhupalakodety, assigned the issue to you.

**Comment by ratnopamc** [comment]
@sindhupalakodety, please raise a PR when you get a chance. Ty.
