### ISSUE TITLE
[Feature] DASK Cluster on EKS

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#67]
- Terraform templates to deploy production ready Dask Cluster on EKS 
- Create a new [K8s Helm addon for Dask Cluster ](https://github.com/dask/helm-chart) for EKS Blueprints repo
- Examples for running Dask jobs 
- Website Doc for the new pattern 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by codesometech** [comment]
I can work on this issue

**Comment by jihed** [comment]
I raised a PR to add Addons for Dask-Operator and Dask-Hub. I am working on example to dask on EKS.
