### ISSUE TITLE
JARK Deployment on Existing EKS cluster Example

### ISSUE THREAD

**Issue by ForeverAngry** [awslabs/data-on-eks#682]
- [ X ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Id like to use the [JARK](https://awslabs.github.io/data-on-eks/docs/blueprints/ai-ml/jark) stack with an existing AWS EKS cluster, without exposing my AWS EKS cluster to the public internet.

I have read, and tested adjusting the JARK deployment a bit.   Before I started really pulling the project apart, i was wondering if anyone had a solution or had come by this before?

**Comment by askulkarni2** [comment]
Its not something we provide out of the box. As you allude, you will have to take some bits out the example we provide to deploy on existing EKS cluster. It should be doable though, just need to pass the cluster parameters where needed.
