### ISSUE TITLE
[Feature] New EMR on EKS Terraform module

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#70]
- Create a new EMR on EKS Terraform module under https://github.com/aws-ia/terraform-aws-emr-containers
- Update all the EMR on EKS Patterns to use external EMR Containers module

**Comment by season1946** [comment]
I got a simile request from melody yang. Will help her for a workshop first and then contribute on this one. @vara-bonthu

**Comment by vara-bonthu** [comment]
This is now sub module on each blueprint. In future we will keep all the reusable add-ons and modules under https://github.com/awslabs/data-on-eks/tree/main/workshop/modules
