### ISSUE TITLE
[Feature] Apache Pinot on Amazon EKS

### ISSUE THREAD

**Issue by mihneaspirescu** [awslabs/data-on-eks#76]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

* Deployment pattern and configuration for Apache Pinot on EKS
* Running Pinot workloads on Amazon EKS with example
* Supporting public blog post 

#### Describe the solution you would like

Apache Pinot is a realtime distributed OLAP datastore, designed to answer OLAP queries with low latency. Pinot is typically used in customer facing analytics.

**Comment by vara-bonthu** [comment]
@wahab-io is working on this PR

**Comment by vara-bonthu** [comment]
Pinot addon has been merged to data addons repo

**Comment by wahab-io** [comment]
Can you merge this PR (https://github.com/aws-ia/terraform-aws-eks-data-addons/pull/15) so that I can change the source from my fork to this project?

Also, implemented some of your recommendations. Removed external LB, updated docs, and installation and cleanup scripts. Ready for review.
