### ISSUE TITLE
[Feature] Apache NiFi on EKS

### ISSUE THREAD

**Issue by codesometech** [awslabs/data-on-eks#80]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
- Deployment pattern for Apache NiFi on EKS
- Running Apache NiFi workload on EKS

#### Describe the solution you would like
Apache NiFi supports powerful and scalable directed graphs of data routing, transformation, and system mediation logic.

**Comment by codesometech** [comment]
I am working on this

**Comment by vara-bonthu** [comment]
This PR has been merged now. Closing the issue
