### ISSUE TITLE
[Question] is it possible to deploy a flink job on EMR on EKS?

### ISSUE THREAD

**Issue by roimor** [awslabs/data-on-eks#93]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

is it possible to deploy a flink job on EMR on EKS?

**Comment by vara-bonthu** [comment]
Flink is not supported with EMR-on-EKS yet. 

@dalbhanj Could you please provide more details?

**Comment by roimor** [comment]
@vara-bonthu @dalbhanj what is then supported in EMR on EKS? only Spark? 
Do you have a roadmap you can share? 

Also, the [docs](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/) are confusing and are not making it clear what is supported or not. The 'Tutorial' section suggests support with Spack/Iceberg/Delta.

**Comment by roimor** [comment]
I also found this issue https://github.com/aws/containers-roadmap/issues/1761 which didn't get any attention from any AWS representative

**Comment by dalbhanj** [comment]
```Also, the [docs](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/) are confusing and are not making it clear what is supported or not```
Forgot to mention, Please see [EMR on EKS release notes](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks-6.9.0.html) to see all supported engines and libraries.

**Comment by roimor** [comment]
is there any estimation when will flink be available on EMR-on-EKS?
