### ISSUE TITLE
[Bug] Getting error when deploying Airflow on EKS

### ISSUE THREAD

**Issue by r-gautam** [awslabs/data-on-eks#97]
Getting below error when deploying EKS and RDS for AIRFLOW with existing VPC.

```
Error: Unsupported attribute
│
│    in module "db":
│  vpc_security_group_ids = [module.security_group.security_group_id]
│     ├────────────────
│     │ module.security_group is a list of object
│
│ Can't access attributes on a list of objects. Did you mean to access attribute "security_group_id" for a specific element of the list, or across all elements of the list?
╵

```

## Versions

- Terraform version:
v1.3.6
- Provider version(s):

```
terraform providers --version
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.51.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

cd /data-on-eks/schedulers/terraform/self-managed-airflow
Disable the VPC module 
Provide the custom inputs for VPC, EKS private subnets and database subnets group name
terraform init
terraform plan
terraform apply \
-var vpc_id=<vpc_id> \
-var private_subnet_ids=<EKS_private_subnet_ID> \
-var db_subnet_group_name=<RDS_subnet_group_name>

## Expected behavior

EKS with RDS deployment should be successful. 

## Actual behavior

EKS deployment is successful but RDS deployment is failing as security group for RDS is not setup.

### Terminal Output Screenshot(s)

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/86465896/215154539-dde15819-12c5-4842-a709-4e2cd895b19b.png">

**Comment by r-gautam** [comment]
Output is list[strings]. So i decided to use Terraform security group [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) instead of module as a workaround.

**Comment by vara-bonthu** [comment]
@r-gautam Please close the issue if its resolved
